import { CityData, HeroStat, FILTER_TAGS } from './types';
export { FILTER_TAGS };

export const HERO_STATS: HeroStat[] = [
  { label: 'CITIES',    value: '2,400+',   icon: '◈', sublabel: 'on record' },
  { label: 'TRAVELERS', value: '128,000+', icon: '◉', sublabel: 'this month' },
  { label: 'REVIEWS',   value: '540,000+', icon: '◆', sublabel: 'verified' },
];

export const CITIES: CityData[] = [
  {
    id: 'seoul',
    name: 'SEOUL',
    country: 'South Korea',
    flag: '🇰🇷',
    colorTheme: '#00ffb3',
    glowClass: 'glow-green',
    shadowClass: 'glow-box-green',
    asciiSkyline: [
      '  ,_,    ╔╗ ╔╗ ╔══╗ ╔╗  ',
      ' |▓|▓|   ║║ ║║ ║██║ ║║  ',
      ' |▓|▓|   ║║ ║║ ║██║ ║║  ',
      ' ▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔ ',
    ],
    weather: 'SUNNY',
    weatherIcon: '☀',
    weatherDesc: 'Clear Sky',
    temperature: '18°C',
    budgetGrade: 'B',
    budgetLabel: 'MODERATE',
    population: '9.7M',
    timezone: 'UTC+9',
    language: 'Korean',
    currency: '₩ KRW',
    nomadScore: 92,
    tags: ['ASIA', 'METROPOLIS', 'WARM'],
    internetSpeed: '250 Mbps',
    costIndex: { rent: 900, food: 350, transport: 60, total: 1500, nomadScore: 92 },
  },
  {
    id: 'tokyo',
    name: 'TOKYO',
    country: 'Japan',
    flag: '🇯🇵',
    colorTheme: '#ff6b9d',
    glowClass: 'glow-pink',
    shadowClass: 'glow-box-pink',
    asciiSkyline: [
      '  /\\  _   /\\  /\\  /\\ ',
      ' /  \\ |  /  \\/  \\/  \\',
      '/    \\|_/    \\    \\   \\',
      '▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔ ',
    ],
    weather: 'PARTLY_CLOUDY',
    weatherIcon: '⛅',
    weatherDesc: 'Partly Cloudy',
    temperature: '22°C',
    budgetGrade: 'C',
    budgetLabel: 'HIGH',
    population: '13.9M',
    timezone: 'UTC+9',
    language: 'Japanese',
    currency: '¥ JPY',
    nomadScore: 94,
    tags: ['ASIA', 'METROPOLIS', 'LUXURY'],
    internetSpeed: '300 Mbps',
    costIndex: { rent: 1400, food: 500, transport: 80, total: 2200, nomadScore: 94 },
  },
  {
    id: 'paris',
    name: 'PARIS',
    country: 'France',
    flag: '🇫🇷',
    colorTheme: '#ffd700',
    glowClass: 'glow-gold',
    shadowClass: 'glow-box-gold',
    asciiSkyline: [
      '    /\\      ___  ___   ',
      '   /  \\    |   ||   |  ',
      '  / /\\ \\   |___||___|  ',
      ' ▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔ ',
    ],
    weather: 'CLOUDY',
    weatherIcon: '☁',
    weatherDesc: 'Overcast',
    temperature: '15°C',
    budgetGrade: 'C',
    budgetLabel: 'HIGH',
    population: '2.1M',
    timezone: 'UTC+2',
    language: 'French',
    currency: '€ EUR',
    nomadScore: 91,
    tags: ['EUROPE', 'METROPOLIS', 'LUXURY'],
    internetSpeed: '180 Mbps',
    costIndex: { rent: 1800, food: 600, transport: 90, total: 2800, nomadScore: 91 },
  },
  {
    id: 'newyork',
    name: 'NEW YORK',
    country: 'United States',
    flag: '🇺🇸',
    colorTheme: '#00d4ff',
    glowClass: 'glow-cyan',
    shadowClass: 'glow-box-cyan',
    asciiSkyline: [
      ' ▐█▌ ▐█▌  ▐██▌ ▐█▌ ▐█▌',
      ' ███ ███  ████ ███ ███',
      ' ███ ███  ████ ███ ███',
      ' ▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔',
    ],
    weather: 'SUNNY',
    weatherIcon: '☀',
    weatherDesc: 'Sunny',
    temperature: '20°C',
    budgetGrade: 'D',
    budgetLabel: 'VERY HIGH',
    population: '8.3M',
    timezone: 'UTC-4',
    language: 'English',
    currency: '$ USD',
    nomadScore: 88,
    tags: ['AMERICAS', 'METROPOLIS', 'LUXURY'],
    internetSpeed: '220 Mbps',
    costIndex: { rent: 3000, food: 700, transport: 130, total: 4500, nomadScore: 88 },
  },
  {
    id: 'sydney',
    name: 'SYDNEY',
    country: 'Australia',
    flag: '🇦🇺',
    colorTheme: '#ff8c42',
    glowClass: 'glow-orange',
    shadowClass: 'glow-box-orange',
    asciiSkyline: [
      '   ___    ╭─╮  ╭──╮   ',
      '  /   \\   │ │  │  │   ',
      ' /     \\__│ │__│  │   ',
      ' ▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔ ',
    ],
    weather: 'SUNNY',
    weatherIcon: '☀',
    weatherDesc: 'Clear',
    temperature: '26°C',
    budgetGrade: 'C',
    budgetLabel: 'HIGH',
    population: '5.3M',
    timezone: 'UTC+10',
    language: 'English',
    currency: '$ AUD',
    nomadScore: 85,
    tags: ['BEACH', 'WARM', 'LUXURY'],
    internetSpeed: '100 Mbps',
    costIndex: { rent: 2200, food: 550, transport: 110, total: 3400, nomadScore: 85 },
  },
  {
    id: 'barcelona',
    name: 'BARCELONA',
    country: 'Spain',
    flag: '🇪🇸',
    colorTheme: '#b983ff',
    glowClass: 'glow-purple',
    shadowClass: 'glow-box-purple',
    asciiSkyline: [
      ' ╔╗  ╔╗   ╔═╗  ╔╗    ',
      ' ║║  ║║   ║ ║  ║║    ',
      ' ╚╝  ╚╝   ╚═╝  ╚╝    ',
      ' ▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔',
    ],
    weather: 'SUNNY',
    weatherIcon: '☀',
    weatherDesc: 'Mediterranean',
    temperature: '24°C',
    budgetGrade: 'B',
    budgetLabel: 'MODERATE',
    population: '1.6M',
    timezone: 'UTC+2',
    language: 'Spanish',
    currency: '€ EUR',
    nomadScore: 90,
    tags: ['EUROPE', 'BEACH', 'WARM', 'BUDGET'],
    internetSpeed: '160 Mbps',
    costIndex: { rent: 1100, food: 420, transport: 70, total: 1800, nomadScore: 90 },
  },
  {
    id: 'lisbon',
    name: 'LISBON',
    country: 'Portugal',
    flag: '🇵🇹',
    colorTheme: '#00b4d8',
    glowClass: 'glow-teal',
    shadowClass: 'glow-box-teal',
    asciiSkyline: [
      '  _   _    ___   ___  ',
      ' | | | |  / _ \\ / _ \\ ',
      ' |_| |_| \\___/ \\___/ ',
      ' ▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔',
    ],
    weather: 'SUNNY',
    weatherIcon: '☀',
    weatherDesc: 'Warm & Sunny',
    temperature: '22°C',
    budgetGrade: 'B',
    budgetLabel: 'MODERATE',
    population: '545K',
    timezone: 'UTC+1',
    language: 'Portuguese',
    currency: '€ EUR',
    nomadScore: 89,
    tags: ['EUROPE', 'BEACH', 'WARM', 'BUDGET'],
    internetSpeed: '140 Mbps',
    costIndex: { rent: 1000, food: 380, transport: 65, total: 1600, nomadScore: 89 },
  },
  {
    id: 'chiangmai',
    name: 'CHIANG MAI',
    country: 'Thailand',
    flag: '🇹🇭',
    colorTheme: '#ffb347',
    glowClass: 'glow-amber',
    shadowClass: 'glow-box-amber',
    asciiSkyline: [
      '  ▲   ___   ▲   ___  ',
      ' /█\\ /   \\ /█\\ /   \\ ',
      '/███\\\\___//███\\\\___/ ',
      '▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔ ',
    ],
    weather: 'TROPICAL',
    weatherIcon: '🌤',
    weatherDesc: 'Tropical',
    temperature: '31°C',
    budgetGrade: 'A',
    budgetLabel: 'BUDGET',
    population: '131K',
    timezone: 'UTC+7',
    language: 'Thai',
    currency: '฿ THB',
    nomadScore: 87,
    tags: ['ASIA', 'MOUNTAIN', 'WARM', 'BUDGET'],
    internetSpeed: '120 Mbps',
    costIndex: { rent: 400, food: 200, transport: 40, total: 800, nomadScore: 87 },
  },
];

export const CTA_TERMINAL_LINES = [
  '> Initializing nomad.protocol...',
  '> Scanning 2,400 cities worldwide...',
  '> Calculating Nomad Score matrix...',
  '> Loading city database...  [DONE]',
  '> Fetching live cost data... [DONE]',
  '> Access granted. Welcome, nomad.',
];

export const CTA_BENEFITS = [
  'Personalized city recommendations',
  'Real-time cost of living alerts',
  'Community of 128K+ nomads',
  'Offline city guides & PDF export',
  'Visa & permit requirement tracker',
  'Co-working space finder & reviews',
];

export const NAV_LINKS = [
  { label: 'HOME',    href: '#' },
  { label: 'EXPLORE', href: '#' },
  { label: 'MAP',     href: '#' },
  { label: 'SAVED',   href: '#' },
  { label: 'JOURNAL', href: '#' },
];

export const FOOTER_LINKS = {
  EXPLORE:   ['Cities', 'Map', 'Rankings', 'Compare'],
  COMMUNITY: ['Forums', 'Discord', 'Newsletter', 'Journal'],
  RESOURCES: ['Blog', 'API Docs', 'Status', 'Changelog'],
  LEGAL:     ['Terms', 'Privacy', 'Cookies', 'Contact'],
};
